### ISSUE TITLE
Can't set keyboardType or initial text

### ISSUE THREAD

**Issue by rfloydb** [ThePantsThief/TBAlertController#3]
I've made some modifications for my project to allow setting of keyboardType and text of the textFields. I would offer a pull request, but I implemented it by adding a property called textFieldInfo consisting of an NSArray of NSDictionaries. I think it might be more elegant to make textFieldInputStrings readwrite and maybe add textFieldKeyboardTypes array, or just allow the passing in of an array of textFields, with some convenience methods to set them up, since it makes the API a bit verbose.

As I said, happy to share my code. Thanks for the head start on this.

**Comment by ThePantsThief** [comment]
`TBAlertController` actually just passes those configuration handlers over to the `UIAlertController` API. Does setting the text not seem to stick or something?

How are you accomplishing this?

**Comment by rfloydb** [comment]
You can control additional text fields no problem, but if you're just using the standard `UIAlertViewStylePlainTextInput`, for example, you have no control over *that* input. My app also sets `autocapitalizationType` on the fields, so my clunky array of dictionaries is already starting to look clunkier.

**Comment by ThePantsThief** [comment]
Well, that's how the standard value works… if you want to customize it, look at `addTextFieldWithConfigurationHandler`

--
Tanner Bennett

**Comment by ThePantsThief** [comment]
Well, that's how the standard value works… if you want to customize it, look at `addTextFieldWithConfigurationHandler`

**Comment by ThePantsThief** [comment]
I've just pushed a new version of the pod, which removes `textFieldInputStrings`, since each button action block is already passed the same array, there's no reason to have it as a property on the alert itself.
