### ISSUE TITLE
Exception on iOS 8 iPad

### ISSUE THREAD

**Issue by ekscrypto** [ThePantsThief/TBAlertController#4]
2015-09-18 21:08:56.248 First@MTS[1196:311891] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x1550ea20>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'

Source to generate the issue:
```
    TBAlertController *alert = [[TBAlertController alloc] initWithStyle:TBAlertControllerStyleActionSheet];
    alert.title   = @"Add a Photo";
    alert.message = @"Pick your image source";
    [alert addOtherButtonWithTitle:@"Camera" buttonAction:^(NSArray *strings) { [self snapPictureFromCamera]; }];
    [alert addOtherButtonWithTitle:@"Photo Library" buttonAction:^(NSArray *strings) { [self snapPictureFromPhotoLibrary]; }];
    [alert setCancelButtonWithTitle:@"Cancel"];
    [alert showFromViewController:self animated:YES completion:NULL];
```

**Comment by ekscrypto** [comment]
The minimum change to make this go away, although placing the view on the top left instead of somewhere logical, is to modify TBAlertController.m around lines 332..

```
        // Add actions to alert controller
        for (UIAlertAction *action in actions)
             [alertController addAction:action];

        if( [UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPad )
        {
            UIPopoverPresentationController *popPresentation = [alertController popoverPresentationController];
            popPresentation.sourceView = viewController.view;
        }

        [viewController presentViewController:alertController animated:animated completion:completion];
        
    }
```

**Comment by ekscrypto** [comment]
I've solved this somewhat cleanly on my end by adding a property to TBAlertController:

```
@property (nonatomic, assign, nullable) UIView *popoverSourceView;
```

Then using a variation of the code previously posted...
```
        if( [UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPad )
        {
            UIPopoverPresentationController *popPresentation = [alertController popoverPresentationController];
            popPresentation.sourceView = self. popoverSourceView ? self. popoverSourceView : viewController.view;
        }
```

And then finally modifying my original code with:
```
    TBAlertController *alert = [[TBAlertController alloc] initWithStyle:TBAlertControllerStyleActionSheet];
    alert.title   = @"Add a Photo";
    alert.message = @"Pick your image source";
    alert.sourceView = cameraButton;
    [alert addOtherButtonWithTitle:@"Camera" buttonAction:^(NSArray *strings) { [self snapPictureFromCamera]; }];
    [alert addOtherButtonWithTitle:@"Photo Library" buttonAction:^(NSArray *strings) { [self snapPictureFromPhotoLibrary]; }];
    [alert setCancelButtonWithTitle:@"Cancel"];
    [alert showFromViewController:self animated:YES completion:NULL];
```

The UIAlertController has the little arrow nicely pointed at my camera button in app, and no exception generated !

**Comment by ThePantsThief** [comment]
Awesome! Submit a PR if you want :) if not I'll implement the fix myself when I get a chance

--
Tanner Bennett
